In [50]:
import pandas as pd

data = {
    'REFUND': ['yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'no'],
    'duration': ['single', 'married', 'single', 'married', 'divorced', 'married', 'divorced', 'single', 'married', 'single'],
    'taxable income': ['125k', '100k', '70k', '120k', '95k', '60k', '220k', '85k', '75k', '90k'],
    'cheat': ['no', 'no', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'yes']
}

df = pd.DataFrame(data)
print(df)

  REFUND  duration taxable income cheat
0    yes    single           125k    no
1     no   married           100k    no
2     no    single            70k    no
3    yes   married           120k    no
4     no  divorced            95k   yes
5     no   married            60k    no
6    yes  divorced           220k    no
7     no    single            85k   yes
8     no   married            75k    no
9     no    single            90k   yes

In [42]:
import pandas as pd

data = {
    'REFUND': ['yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'no'],
    'duration': ['single', 'married', 'single', 'married', 'divorced', 'married', 'divorced', 'single', 'married', 'single']
     'taxable income': ['125k', '100k', '70k', '120k', '95k', '60k', '220k', '85k', '75k', '90k'],
    'cheat': ['no', 'no', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'yes']
}
}

df = pd.DataFrame(data)
print(df.loc[0])
print(df.loc[4])
print(df.loc[7])
print(df.loc[8])

REFUND         yes
duration    single
Name: 0, dtype: object
REFUND            no
duration    divorced
Name: 4, dtype: object
REFUND          no
duration    single
Name: 7, dtype: object
REFUND           no
duration    married
Name: 8, dtype: object

In [52]:
import pandas as pd

data = {
    'REFUND': ['yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'no'],
    'duration': ['single', 'married', 'single', 'married', 'divorced', 'married', 'divorced', 'single', 'married', 'single'],
     'taxable income': ['125k', '100k', '70k', '120k', '95k', '60k', '220k', '85k', '75k', '90k'],
    'cheat': ['no', 'no', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'yes']
}
df = pd.DataFrame(data)
print(df.iloc[3:8])
print(df.iloc[4:9, 0:2])
print(df.iloc[:, 0:2])

  REFUND  duration taxable income cheat
3    yes   married           120k    no
4     no  divorced            95k   yes
5     no   married            60k    no
6    yes  divorced           220k    no
7     no    single            85k   yes
  REFUND  duration
4     no  divorced
5     no   married
6    yes  divorced
7     no    single
8     no   married
  REFUND  duration
0    yes    single
1     no   married
2     no    single
3    yes   married
4     no  divorced
5     no   married
6    yes  divorced
7     no    single
8     no   married
9     no    single

In [6]:
import pandas as pd
df=pd.read_csv('Iris.csv')
df.head()
print(df.to_string())

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
0      1            5.1           3.5            1.4           0.2      Iris-setosa
1      2            4.9           3.0            1.4           0.2      Iris-setosa
2      3            4.7           3.2            1.3           0.2      Iris-setosa
3      4            4.6           3.1            1.5           0.2      Iris-setosa
4      5            5.0           3.6            1.4           0.2      Iris-setosa
5      6            5.4           3.9            1.7           0.4      Iris-setosa
6      7            4.6           3.4            1.4           0.3      Iris-setosa
7      8            5.0           3.4            1.5           0.2      Iris-setosa
8      9            4.4           2.9            1.4           0.2      Iris-setosa
9     10            4.9           3.1            1.5           0.1      Iris-setosa
10    11            5.4           3.7            1.5           0.2      Iris-setosa
11    12            4.8           3.4            1.6           0.2      Iris-setosa
12    13            4.8           3.0            1.4           0.1      Iris-setosa
13    14            4.3           3.0            1.1           0.1      Iris-setosa
14    15            5.8           4.0            1.2           0.2      Iris-setosa
15    16            5.7           4.4            1.5           0.4      Iris-setosa
16    17            5.4           3.9            1.3           0.4      Iris-setosa
17    18            5.1           3.5            1.4           0.3      Iris-setosa
18    19            5.7           3.8            1.7           0.3      Iris-setosa
19    20            5.1           3.8            1.5           0.3      Iris-setosa
20    21            5.4           3.4            1.7           0.2      Iris-setosa
21    22            5.1           3.7            1.5           0.4      Iris-setosa
22    23            4.6           3.6            1.0           0.2      Iris-setosa
23    24            5.1           3.3            1.7           0.5      Iris-setosa
24    25            4.8           3.4            1.9           0.2      Iris-setosa
25    26            5.0           3.0            1.6           0.2      Iris-setosa
26    27            5.0           3.4            1.6           0.4      Iris-setosa
27    28            5.2           3.5            1.5           0.2      Iris-setosa
28    29            5.2           3.4            1.4           0.2      Iris-setosa
29    30            4.7           3.2            1.6           0.2      Iris-setosa
30    31            4.8           3.1            1.6           0.2      Iris-setosa
31    32            5.4           3.4            1.5           0.4      Iris-setosa
32    33            5.2           4.1            1.5           0.1      Iris-setosa
33    34            5.5           4.2            1.4           0.2      Iris-setosa
34    35            4.9           3.1            1.5           0.1      Iris-setosa
35    36            5.0           3.2            1.2           0.2      Iris-setosa
36    37            5.5           3.5            1.3           0.2      Iris-setosa
37    38            4.9           3.1            1.5           0.1      Iris-setosa
38    39            4.4           3.0            1.3           0.2      Iris-setosa
39    40            5.1           3.4            1.5           0.2      Iris-setosa
40    41            5.0           3.5            1.3           0.3      Iris-setosa
41    42            4.5           2.3            1.3           0.3      Iris-setosa
42    43            4.4           3.2            1.3           0.2      Iris-setosa
43    44            5.0           3.5            1.6           0.6      Iris-setosa
44    45            5.1           3.8            1.9           0.4      Iris-setosa
45    46            4.8           3.0            1.4           0.3      Iris-setosa
46    47            5.1           3.8            1.6           0.2      Iris-setosa
47    48            4.6           3.2            1.4           0.2      Iris-setosa
48    49            5.3           3.7            1.5           0.2      Iris-setosa
49    50            5.0           3.3            1.4           0.2      Iris-setosa
50    51            7.0           3.2            4.7           1.4  Iris-versicolor
51    52            6.4           3.2            4.5           1.5  Iris-versicolor
52    53            6.9           3.1            4.9           1.5  Iris-versicolor
53    54            5.5           2.3            4.0           1.3  Iris-versicolor
54    55            6.5           2.8            4.6           1.5  Iris-versicolor
55    56            5.7           2.8            4.5           1.3  Iris-versicolor
56    57            6.3           3.3            4.7           1.6  Iris-versicolor
57    58            4.9           2.4            3.3           1.0  Iris-versicolor
58    59            6.6           2.9            4.6           1.3  Iris-versicolor
59    60            5.2           2.7            3.9           1.4  Iris-versicolor
60    61            5.0           2.0            3.5           1.0  Iris-versicolor
61    62            5.9           3.0            4.2           1.5  Iris-versicolor
62    63            6.0           2.2            4.0           1.0  Iris-versicolor
63    64            6.1           2.9            4.7           1.4  Iris-versicolor
64    65            5.6           2.9            3.6           1.3  Iris-versicolor
65    66            6.7           3.1            4.4           1.4  Iris-versicolor
66    67            5.6           3.0            4.5           1.5  Iris-versicolor
67    68            5.8           2.7            4.1           1.0  Iris-versicolor
68    69            6.2           2.2            4.5           1.5  Iris-versicolor
69    70            5.6           2.5            3.9           1.1  Iris-versicolor
70    71            5.9           3.2            4.8           1.8  Iris-versicolor
71    72            6.1           2.8            4.0           1.3  Iris-versicolor
72    73            6.3           2.5            4.9           1.5  Iris-versicolor
73    74            6.1           2.8            4.7           1.2  Iris-versicolor
74    75            6.4           2.9            4.3           1.3  Iris-versicolor
75    76            6.6           3.0            4.4           1.4  Iris-versicolor
76    77            6.8           2.8            4.8           1.4  Iris-versicolor
77    78            6.7           3.0            5.0           1.7  Iris-versicolor
78    79            6.0           2.9            4.5           1.5  Iris-versicolor
79    80            5.7           2.6            3.5           1.0  Iris-versicolor
80    81            5.5           2.4            3.8           1.1  Iris-versicolor
81    82            5.5           2.4            3.7           1.0  Iris-versicolor
82    83            5.8           2.7            3.9           1.2  Iris-versicolor
83    84            6.0           2.7            5.1           1.6  Iris-versicolor
84    85            5.4           3.0            4.5           1.5  Iris-versicolor
85    86            6.0           3.4            4.5           1.6  Iris-versicolor
86    87            6.7           3.1            4.7           1.5  Iris-versicolor
87    88            6.3           2.3            4.4           1.3  Iris-versicolor
88    89            5.6           3.0            4.1           1.3  Iris-versicolor
89    90            5.5           2.5            4.0           1.3  Iris-versicolor
90    91            5.5           2.6            4.4           1.2  Iris-versicolor
91    92            6.1           3.0            4.6           1.4  Iris-versicolor
92    93            5.8           2.6            4.0           1.2  Iris-versicolor
93    94            5.0           2.3            3.3           1.0  Iris-versicolor
94    95            5.6           2.7            4.2           1.3  Iris-versicolor
95    96            5.7           3.0            4.2           1.2  Iris-versicolor
96    97            5.7           2.9            4.2           1.3  Iris-versicolor
97    98            6.2           2.9            4.3           1.3  Iris-versicolor
98    99            5.1           2.5            3.0           1.1  Iris-versicolor
99   100            5.7           2.8            4.1           1.3  Iris-versicolor
100  101            6.3           3.3            6.0           2.5   Iris-virginica
101  102            5.8           2.7            5.1           1.9   Iris-virginica
102  103            7.1           3.0            5.9           2.1   Iris-virginica
103  104            6.3           2.9            5.6           1.8   Iris-virginica
104  105            6.5           3.0            5.8           2.2   Iris-virginica
105  106            7.6           3.0            6.6           2.1   Iris-virginica
106  107            4.9           2.5            4.5           1.7   Iris-virginica
107  108            7.3           2.9            6.3           1.8   Iris-virginica
108  109            6.7           2.5            5.8           1.8   Iris-virginica
109  110            7.2           3.6            6.1           2.5   Iris-virginica
110  111            6.5           3.2            5.1           2.0   Iris-virginica
111  112            6.4           2.7            5.3           1.9   Iris-virginica
112  113            6.8           3.0            5.5           2.1   Iris-virginica
113  114            5.7           2.5            5.0           2.0   Iris-virginica
114  115            5.8           2.8            5.1           2.4   Iris-virginica
115  116            6.4           3.2            5.3           2.3   Iris-virginica
116  117            6.5           3.0            5.5           1.8   Iris-virginica
117  118            7.7           3.8            6.7           2.2   Iris-virginica
118  119            7.7           2.6            6.9           2.3   Iris-virginica
119  120            6.0           2.2            5.0           1.5   Iris-virginica
120  121            6.9           3.2            5.7           2.3   Iris-virginica
121  122            5.6           2.8            4.9           2.0   Iris-virginica
122  123            7.7           2.8            6.7           2.0   Iris-virginica
123  124            6.3           2.7            4.9           1.8   Iris-virginica
124  125            6.7           3.3            5.7           2.1   Iris-virginica
125  126            7.2           3.2            6.0           1.8   Iris-virginica
126  127            6.2           2.8            4.8           1.8   Iris-virginica
127  128            6.1           3.0            4.9           1.8   Iris-virginica
128  129            6.4           2.8            5.6           2.1   Iris-virginica
129  130            7.2           3.0            5.8           1.6   Iris-virginica
130  131            7.4           2.8            6.1           1.9   Iris-virginica
131  132            7.9           3.8            6.4           2.0   Iris-virginica
132  133            6.4           2.8            5.6           2.2   Iris-virginica
133  134            6.3           2.8            5.1           1.5   Iris-virginica
134  135            6.1           2.6            5.6           1.4   Iris-virginica
135  136            7.7           3.0            6.1           2.3   Iris-virginica
136  137            6.3           3.4            5.6           2.4   Iris-virginica
137  138            6.4           3.1            5.5           1.8   Iris-virginica
138  139            6.0           3.0            4.8           1.8   Iris-virginica
139  140            6.9           3.1            5.4           2.1   Iris-virginica
140  141            6.7           3.1            5.6           2.4   Iris-virginica
141  142            6.9           3.1            5.1           2.3   Iris-virginica
142  143            5.8           2.7            5.1           1.9   Iris-virginica
143  144            6.8           3.2            5.9           2.3   Iris-virginica
144  145            6.7           3.3            5.7           2.5   Iris-virginica
145  146            6.7           3.0            5.2           2.3   Iris-virginica
146  147            6.3           2.5            5.0           1.9   Iris-virginica
147  148            6.5           3.0            5.2           2.0   Iris-virginica
148  149            6.2           3.4            5.4           2.3   Iris-virginica
149  150            5.9           3.0            5.1           1.8   Iris-virginica

In [10]:
import pandas as pd
df=pd.read_csv('Iris.csv')
df.head()
print(df.drop(df.columns[4],axis=1,inplace=True))
print(df.drop(4,axis=0,inplace=True))

None
None

In [8]:
import pandas as pd

# Creating employee dataset
data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": ["2020-03-15", "2017-07-19", "2013-06-01", "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}

# Convert dictionary to DataFrame
df = pd.DataFrame(data)

# Save to CSV file
df.to_csv("employees.csv", index=False)

print("employees.csv file created successfully!")
import pandas as pd
# Load the dataset
df = pd.read_csv("employees.csv")
# (a) Shape of the DataFrame
print("Shape of the DataFrame (rows, columns):", df.shape)
# (b) Summary of the DataFrame
print("\nSummary of the DataFrame:")
print(df.info())
# (c) Descriptive statistics
print("\nDescriptive Statistics:")
print(df.describe())
# (d) First 5 rows
print("\nFirst 5 rows of the dataset:")
print(df.head())
#  Last 3 rows
print("\nLast 3 rows of the dataset:")
print(df.tail(3))

# (e) Calculate statistics
average_salary = df["Salary"].mean()
total_bonus = df["Bonus"].sum()
youngest_age = df["Age"].min()
highest_rating = df["Rating"].max()

print("Average Salary:", average_salary)
print("Total Bonus Paid:", total_bonus)
print("Youngest Employee Age:", youngest_age)
print("Highest Performance Rating:", highest_rating)

# (f) Sort DataFrame by Salary in descending order
df_sorted = df.sort_values(by="Salary", ascending=False)
print("\nDataFrame sorted by Salary in descending order:")
print(df_sorted)

# (g) Categorize employees based on performance rating
def categorize_performance(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

df["Performance_Category"] = df["Rating"].apply(categorize_performance)
print("\nAdded Performance_Category column:")
print(df[["Name", "Rating", "Performance_Category"]])

# (h) Identify missing values
missing_values = df.isnull().sum()
print("\nMissing values in each column:")
print(missing_values)

# (i) Rename Employee_ID column to ID
df.rename(columns={"Employee_ID": "ID"}, inplace=True)
print("\nRenamed Employee_ID to ID:")
print(df.head())

# (j) Find employees with more than 5 years of experience
experienced_employees = df[df["Years_of_Experience"] > 5]
print("\nEmployees with more than 5 years of experience:")
print(experienced_employees)

# Find employees who belong to the IT department
it_employees = df[df["Department"] == "IT"]
print("\nEmployees in the IT department:")
print(it_employees)

# (k) Add a new column 'Tax' which deducts 10% of Salary
df["Tax"] = df["Salary"] * 0.10
print("\nAdded Tax column (10% deduction from Salary):")
print(df[["Name", "Salary", "Tax"]])

# (l) Save the modified DataFrame to a new CSV file
df.to_csv("employees_modified.csv", index=False)
print("\nModified dataset saved as 'employees_modified.csv'")

employees.csv file created successfully!
Shape of the DataFrame (rows, columns): (5, 10)

Summary of the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes
None

Descriptive Statistics:
       Employee_ID        Age       Salary  Years_of_Experience   Bonus  \
count     5.000000   5.000000      5.00000             5.000000     5.0
mean    103.000000  34.000000  60000.00000             7.400000  5500.0
std       1.581139   5.612486   7905.69415             3.847077  1000.0
min     101.000000  28.000000  50000.00000             3.000000  4500.0
25%     102.000000  29.000000  55000.00000             4.000000  5000.0
50%     103.000000  34.000000  60000.00000             8.000000  5000.0
75%     104.000000  38.000000  65000.00000            10.000000  6000.0
max     105.000000  41.000000  70000.00000            12.000000  7000.0

         Rating
count  5.000000
mean   4.100000
std    0.494975
min    3.500000
25%    3.800000
50%    4.000000
75%    4.500000
max    4.700000

First 5 rows of the dataset:
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

Last 3 rows of the dataset:
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5
Average Salary: 60000.0
Total Bonus Paid: 27500
Youngest Employee Age: 28
Highest Performance Rating: 4.7

DataFrame sorted by Salary in descending order:
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
3          104    Diana  Marketing   28   55000                    3
0          101    Alice         HR   29   50000                    4

  Joining_Date  Gender  Bonus  Rating
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
4   2010-11-25    Male   5000     3.5
3   2021-02-10  Female   4500     4.7
0   2020-03-15  Female   5000     4.5

Added Performance_Category column:
      Name  Rating Performance_Category
0    Alice     4.5            Excellent
1      Bob     4.0                 Good
2  Charlie     3.8              Average
3    Diana     4.7            Excellent
4   Edward     3.5              Average

Missing values in each column:
Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

Renamed Employee_ID to ID:
    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
0  101    Alice         HR   29   50000                    4   2020-03-15
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
3  104    Diana  Marketing   28   55000                    3   2021-02-10
4  105   Edward      Sales   38   60000                   12   2010-11-25

   Gender  Bonus  Rating Performance_Category
0  Female   5000     4.5            Excellent
1    Male   7000     4.0                 Good
2    Male   6000     3.8              Average
3  Female   4500     4.7            Excellent
4    Male   5000     3.5              Average

Employees with more than 5 years of experience:
    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25

  Gender  Bonus  Rating Performance_Category
1   Male   7000     4.0                 Good
2   Male   6000     3.8              Average
4   Male   5000     3.5              Average

Employees in the IT department:
    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01

  Gender  Bonus  Rating Performance_Category
1   Male   7000     4.0                 Good
2   Male   6000     3.8              Average

Added Tax column (10% deduction from Salary):
      Name  Salary     Tax
0    Alice   50000  5000.0
1      Bob   70000  7000.0
2  Charlie   65000  6500.0
3    Diana   55000  5500.0
4   Edward   60000  6000.0

Modified dataset saved as 'employees_modified.csv'